config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  get "book_flight", to: "bookings#new"
  post "search", to: "bookings#search"
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :show, :create]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: :from_airport_id, class_name: "Flight"
  has_many :arriving_flights, foreign_key: :to_airport_id, class_name: "Flight"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, inverse_of: :booking, dependent: :destroy
  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :from_airport, foreign_key: :from_airport_id, class_name: "Airport"
  belongs_to :to_airport, foreign_key: :to_airport_id, class_name: "Airport"
  has_many :bookings
  scope :sorted_dates, -> { where("departure > ?", Time.now).order(:departure) }
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  before_save :downcase_email

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include FlightsHelper
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @flight = Flight.find_by(id: params[:results][:chosen_flight])
    params[:results][:num_passengers].to_i.times { @booking.passengers.build }
  end

  def create
    if params[:commit] == "Submit Information"
      @flight = Flight.find_by(id: params[:flight_number])
      @booking = @flight.bookings.build(booking_params)
      if @booking&.save
        @booking.passengers.each do |passenger|
          PassengerMailer.with(booking: @booking).ticket_email(passenger).deliver_later
        end
        flash[:success] = "Flight booked!"
        redirect_to booking_path(@booking)
      else
        render :new
      end
    elsif params[:commit] == "Change Details"
      redirect_to root_path
    end
  end

  def show
    @booking = Booking.find_by(id: params[:id])
  end

  def search
    @email = params[:search_booking].downcase unless params[:search_booking].nil?
    @booked_flight = Booking.find_by(passengers: Passenger.find_by("email = ?", @email))
    if !@booked_flight.nil?
      redirect_to booking_path(@booked_flight), booked: @booked_flight
    else
      flash[:danger] = "There are no flights booked under this email."
      redirect_to request.referrer
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_number,
                                    passengers_attributes: [:first_name, :last_name, :email])
  end

  def create_passenger

  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def new
  end

  def index
    unless params[:flight].nil?
      @from_airport = Airport.where(code: params[:flight][:from_airport]).first
      @to_airport = Airport.where(code: params[:flight][:to_airport]).first
      if params[:flight][:any_date] == "1"
        @found_flights = flight_any_date.sorted_dates
      else
        @depart = params[:flight][:date].to_date
        @found_flights = flight_with_date.sorted_dates
      end
      if @from_airport == @to_airport
        flash.now[:warning] = "You cannot select the same airport."
      end
    end
  end

  private

  def flight_params
    params.require(:flight).permit(:from_airport, :to_airport, :passengers, :date)
  end

  def flight_with_date
    Flight.where("from_airport_id = ? AND to_airport_id = ? AND departure BETWEEN ? AND ?",
                 @from_airport.id, @to_airport.id, @depart.beginning_of_day, @depart.end_of_day).all
  end

  def flight_any_date
    Flight.where("from_airport_id = ? AND to_airport_id = ?", @from_airport.id, @to_airport.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title_helper(page_title = '')
    base_title = "Simple Flights"
    if page_title.empty?
      base_title
    else
      "#{page_title} - #{base_title}"
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
  def keep_selected_forms(attr)
    unless params[:flight].nil?
      if params[:flight][attr.to_sym].nil? || params[:flight][attr.to_sym].empty?
        1
      else
        params[:flight][attr.to_sym]
      end
    end
  end

  def format_date_time(datetime)
    datetime.strftime("%-m/%d/%Y - %I:%M%P")
  end
end

app/views/bookings/_booking_form.html.erb
<div class="booking-form">
  <%= form_with model: @booking, url: bookings_path, local: true, method: :post do |f| %>
    <div class="form-row flight-info">
      <div class="form-group col-md-3">
        <%= f.label :flight_id %>
        <%= f.text_field :flight_id, class: "form-control", disabled: true,
                         value: flight.id %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :departing %>
        <%= f.text_field :departing, class: "form-control", disabled: true,
                         value: flight.from_airport.name %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :arriving %>
        <%= f.text_field :arriving, class: "form-control", disabled: true,
                         value: flight.to_airport.name %>
      </div>
      <div class="form-group col-md-3">
        <%= f.label :time %>
        <%= f.text_field :time, class: "form-control", disabled: true,
                         value: format_date_time(flight.departure) %>
      </div>
    </div>
    <%= f.fields_for :passengers do |field| %>
      <div class="booking-info">
        <div class="form-row">
          <div class="passenger-info">
            <%= "Passenger" %>
          </div>
          <div class="form-group">
            <div class="col-md-4 field-col">
              <%= field.label :first_name %>
              <%= field.text_field :first_name, class: "form-control", required: true %>
            </div>
            <div class="col-md-4 field-col">
              <%= field.label :last_name %>
              <%= field.text_field :last_name, class: "form-control", required: true %>
            </div>
            <div class="col field-col" id="email-col">
              <%= field.label :email %>
              <%= field.email_field :email, class: "form-control", required: true %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <%= hidden_field_tag :flight_number, @flight.id %>
    <%= f.submit "Submit Information", class: "btn btn-primary btn-passenger" %>
  <% end %>
  <%= form_with scope: :restart, url: bookings_path, local: true do |f| %>
    <%= f.submit "Change Details", class: "btn btn-primary btn-restart" %>
  <% end %>
</div>

app/views/bookings/new.html.erb
<% provide(:title, ) %>
<div class="row col-md-offset-2">
  <h3 class="mb-3">Flight Details</h3>
  <%= render 'booking_form', flight: @flight, num_passengers: @passengers %>
</div>

app/views/bookings/show.html.erb
<div class="col-md-offset-2">
  <div class="booking-results">
    <dt class="col-sm-3">Flight</dt>
    <dd class="col-sm-9"><%= @booking.flight.id %></dd>
    <dt class="col-sm-3">Departing</dt>
    <dd class="col-sm-9"><%= @booking.flight.from_airport.name %></dd>
    <dt class="col-sm-3">Arriving</dt>
    <dd class="col-sm-9"><%= @booking.flight.to_airport.name %></dd>
    <dt class="col-sm-3">Time</dt>
    <dd class="col-sm-9"><%= format_date_time(@booking.flight.departure) %></dd>
  </div>
  <div class="booking-results-passengers">
    <% @booking.passengers.each do |passenger| %>
      <dt class="col-sm-3">Passenger</dt>
      <dd class="col-sm-9">
        <p><%= passenger.first_name %></p>
        <p><%= passenger.last_name %></p>
        <p><%= passenger.email %></p>
      </dd>
    <% end %>
  </div>
</div>

app/views/flights/_search_form.html.erb
<div class="search-form row row-no-gutters">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with scope: :flight, url: flights_path, local: true, method: :get do |f| %>
      <div class="form-group">
        <%= f.label "Flights from", class: 'col-md-12' %>
        <%= f.collection_select :from_airport, Airport.all, :code, :name,
                                { prompt: true, class: "form-control",
                                selected: keep_selected_forms("from_airport")}, { required: true } %>
      </div>
      <div class="form-group">
        <%= f.label "Flights to", class: 'col-md-12' %>
        <%= f.collection_select :to_airport, Airport.all, :code, :name,
                                { prompt: true, class: "form-control",
                                selected: keep_selected_forms("to_airport")}, { required: true } %>
      </div>
      <div class="form-group">
        <%= f.label "Number of Passengers", class: 'col-md-12' %>
        <%= f.select :num_passengers, options_for_select(1..4, required: true,
                                  selected: keep_selected_forms("num_passengers")), class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label "Departing date & time", class: 'col-md-12' %>
        <%= f.date_field :date, min: Date.today + 1, max: Date.today + 30, value: Date.today + 1,
                         required: true, id: "date-select" %>
      </div>
      <div class="form-group">
        <%= f.label :any_date, class: "checkbox inline" do %>
          <%= f.check_box :any_date, id: "any-date" %>
          <span>Search all upcoming flights</span>
        <% end %>
      </div>
        <%= f.submit "Search Flights", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/flights/_search_results.html.erb
<%= form_with scope: :results, url: book_flight_path, local: true, method: :get do |f| %>
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th></th>
        <th scope="col">Flight from</th>
        <th scope="col">Flight to</th>
        <th scope="col">Duration (min.)</th>
        <th scope="col">Date & Time</th>
      </tr>
    </thead>
    <tbody>
    <% found_flights.each do |flight| %>
      <tr>
        <td><%= f.radio_button :chosen_flight, flight.id %></td>
        <td><%= "#{flight.from_airport.name} - #{flight.from_airport.code}" %></td>
        <td><%= "#{flight.to_airport.name} - #{flight.to_airport.code}" %></td>
        <td><%= flight.duration %></td>
        <td><%= format_date_time(flight.departure)  %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <%= f.hidden_field :num_passengers, value: params[:flight][:num_passengers] %>
  <%= f.submit "Choose Flight", class: "btn btn-primary col-md-offset-3" %>
<% end %>

app/views/flights/index.html.erb
<% provide(:title, "Search Flights") %>
<%= render 'flights/search_form' %>

<div class="search-results">
  <% unless @found_flights.blank? %>
    <h3 class="col-md-offset-3" id="search-header">Search Results</h3>
    <%= render "flights/search_results", found_flights: @found_flights %>
  <% end %>
</div>

app/views/layouts/_head.html.erb
<head>
  <title><%= title_helper(yield(:title)) %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-dark">
  <div class="container">
    <%= link_to "Simple Flights", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "https://github.com/ellielle/flight-booker" do %>
            <%= octicon "mark-github" %>
          <% end %>
        </li>
      </ul>
      <div class="search-form">
        <ul class="nav navbar-nav navbar-right">
          <%= form_with url: search_path, local: true, method: :post do |f| %>
            <%= f.text_field :search_booking, class: "form-inline", placeholder: "Search Flight by Email..." %>
            <%= f.submit "Search", class: "btn btn-primary" %>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <%= render 'layouts/head' %>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_head.html.erb
<head>
  <title>FlightBooker</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>